build/azure-pipelines/build-common.yml
build/azure-pipelines/build-product.yml

Add an ARM64 Linux and ARM Windows binary to the release

---

pkg/sqlcmd/batch_test.go
pkg/sqlcmd/parse.go
pkg/sqlcmd/variables.go
pkg/sqlcmd/variables_test.go

allow _ and - in variable names

---

pkg/sqlcmd/format.go

fix money column format

---

build/azure-pipelines/build-product.yml

This commit adds a task to create a github release using an oAuth authentication-based service connection.

Update build-product.yml for Azure Pipelines

---

README.md

This commit documents the breaking change as described in detail in #103

Update breaking change for '-i' switch

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/parse.go
pkg/sqlcmd/sqlcmd_test.go

support variables in some commands

---

pkg/sqlcmd/sqlcmd.go

exit on ctrl-c

---

cmd/sqlcmd/main_test.go

Fix tests to run cross-plat

---

build/azure-pipelines/build-product.yml

This PR is created to investigate and update the esrpcodesigning task

Fix esrpcodesigning task

---

NOTICE.md
build/NOTICE.header
build/NOTICE.tpl
build/azure-pipelines/build-common.yml
build/build.cmd
build/build.sh

Per OSS requirements at Microsoft.

Generate NOTICE file for licenses

---

build/azure-pipelines/build-product.yml

Temporary workaround due #224.

Temp disable Windows ARM build due to named pipes

---

build/azure-pipelines/package-common-create.yml

Fix Package pipeline

---

build/azure-pipelines/build-product.yml

Remove '.exe' ext from binary name

Fix LinuxS390 binary name

---

build/azure-pipelines/build-product.yml
cmd/modern/main.go
cmd/modern/main_test.go
cmd/modern/root/config/connection-strings.go
cmd/modern/root/config/connection-strings_test.go
internal/buffer/memory-buffer.go
internal/buffer/memory-buffer_test.go
internal/cmdparser/test.go
internal/sql/interface.go
internal/sql/mock.go
internal/sql/mssql.go

Add --database to sqlcmd config cs

---

cmd/sqlcmd/sqlcmd.go

C:\src>sqlcmd --version
sqlcmd: local-build
Legal docs and information: aka.ms/SqlcmdLegal
Third party notices: aka.ms/SqlcmdNotices

Add Legal and Notices to --version

---

cmd/sqlcmd/sqlcmd.go
internal/sql/mssql.go
pkg/sqlcmd/sqlcmd.go

ensure Console.Close on exit

---

internal/translations/locales/out.gotext.de-de.json
internal/translations/locales/out.gotext.es-es.json
internal/translations/locales/out.gotext.fr-fr.json
internal/translations/locales/out.gotext.it-it.json
internal/translations/locales/out.gotext.ja-jp.json
internal/translations/locales/out.gotext.ko-kr.json
internal/translations/locales/out.gotext.pt-br.json
internal/translations/locales/out.gotext.qps-ploc.json
internal/translations/locales/out.gotext.qps-plocm.json
internal/translations/locales/out.gotext.ru-ru.json
internal/translations/locales/out.gotext.zh-cn.json
internal/translations/locales/out.gotext.zh-tw.json

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 615: Build ID 200924

---

internal/translations/locales/de-de/out.gotext.json
internal/translations/locales/es-es/out.gotext.json
internal/translations/locales/fr-fr/out.gotext.json
internal/translations/locales/it-it/out.gotext.json
internal/translations/locales/ja-jp/out.gotext.json
internal/translations/locales/ko-kr/out.gotext.json
internal/translations/locales/pt-br/out.gotext.json
internal/translations/locales/qps-ploc/out.gotext.json
internal/translations/locales/qps-plocm/out.gotext.json
internal/translations/locales/ru-ru/out.gotext.json
internal/translations/locales/zh-cn/out.gotext.json
internal/translations/locales/zh-tw/out.gotext.json

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 615: Build ID 200939

---

build/build.cmd
cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go
internal/translations/catalog.go
internal/translations/locales/de-DE/out.gotext.json
internal/translations/locales/en-US/out.gotext.json
internal/translations/locales/es-ES/out.gotext.json
internal/translations/locales/fr-FR/out.gotext.json
internal/translations/locales/it-IT/out.gotext.json
internal/translations/locales/ja-JP/out.gotext.json
internal/translations/locales/ko-KR/out.gotext.json
internal/translations/locales/pt-BR/out.gotext.json
internal/translations/locales/ru-RU/out.gotext.json
internal/translations/locales/zh-CN/out.gotext.json
internal/translations/locales/zh-TW/out.gotext.json

Add errors for mutually exclusive parameters

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230622055845313 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230622055845313 to main

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230626041639336 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230626041639336 to main

---

internal/translations/LCL/de-DE/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230627042041264 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230627042041264 to main

---

internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230705041700160 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230705041700160 to main

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230707041626499 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230707041626499 to main

---

internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230708042107144 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230708042107144 to main

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230710043115796 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230710043115796 to main

---

internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230711041639056 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230711041639056 to main

---

internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230714041719426 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230714041719426 to main

---

internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230716041631903 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230716041631903 to main

---

internal/translations/LCL/fr-FR/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230725041656166 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230725041656166 to main

---

internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230728041805950 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230728041805950 to main

---

internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230729041700600 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230729041700600 to main

---

internal/translations/LCL/it-IT/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230801041707448 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20230801041707448 to main

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231006041755927 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231006041755927 to main

---

internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231007042222855 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231007042222855 to main

---

go.mod
go.sum
internal/container/controller.go

github.com/docker/docker from v20.10.24 to v24.0.6

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231116051839698 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231116051839698 to main

---

internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231117051803391 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20231117051803391 to main

---

NOTICE.md
go.mod
go.sum

this PR addresses this issue: #507

update docker/docker version to v24.0.9

---

internal/translations/LCL/de-DE/out.gotext.json.lcl
internal/translations/LCL/es-ES/out.gotext.json.lcl
internal/translations/LCL/fr-FR/out.gotext.json.lcl
internal/translations/LCL/it-IT/out.gotext.json.lcl
internal/translations/LCL/ja-JP/out.gotext.json.lcl
internal/translations/LCL/ko-KR/out.gotext.json.lcl
internal/translations/LCL/pt-BR/out.gotext.json.lcl
internal/translations/LCL/ru-RU/out.gotext.json.lcl
internal/translations/LCL/zh-CN/out.gotext.json.lcl
internal/translations/LCL/zh-TW/out.gotext.json.lcl

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20250714205148417 to main with localized lcls

LEGO: Pull request from juno/hb_d639428f-b4f7-44e1-9f59-4eea699b1621_20250714205148417 to main
