cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/format.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go
pkg/sqlcmd/variables.go

This is a somewhat cleaner implementation for #37.
I have also added `--driver-logging-level` switch so sqlcmd can print out the `go-mssqldb` driver traces to help debug it.

implement error handling switches

---

.pipelines/TestSql2017.yml
.pipelines/include-runtests-linux.yml
README.md
cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
pkg/sqlcmd/azure_auth.go
pkg/sqlcmd/sqlcmd_test.go

go-sqlcmd doesn't need a custom connector implementation now that `go-mssqldb` has an azuread connector.
I've also cleaned up the test pipeline to actually publish test results.

Switch out AAD auth implementation to leverage go-mssqldb

---

README.md
cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
go.mod
go.sum
pkg/sqlcmd/azure_auth.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/connect.go
pkg/sqlcmd/format_test.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

`:Connect` implementation uses the same command line parser as `main`. I've added a `-G` to enable AAD auth. 
I've also created a `Console` interface to enable future replacement of `readline` with something more modern.
Fixes #50

Implement connect command and password prompt

---

.github/workflows/pr-validation.yml

This may not work but it's a start. I looked around for how to test new actions on non-default branches and it seems rather complicated to try. Once I have it showing up in the workflows list I can iterate on it in a separate branch

add a PR validation test action

---

pkg/sqlcmd/format_test.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

Keep one connection open for the lifetime of sqlcmd

---

cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
go.mod
go.sum

Fixes #67 
thx to @stuartpa for blazing the trail

fix -h switch

---

pkg/sqlcmd/sqlcmd_test.go
pkg/sqlcmd/util.go
pkg/sqlcmd/variables_test.go

Fixes #66 
Current code uses the wrong separator for server\instance connection strings.

use correct divider for instance name

---

build/azure-pipelines/package-product.yml
release/linux/deb/README.md
release/linux/deb/build-pkg.sh
release/linux/deb/pipeline-test.sh
release/linux/deb/pipeline.sh
release/linux/deb/prepare-rules.sh
release/linux/rpm/README.md

This PR builds and signs the sqlcmd .deb package for Apt-get (Ubuntu/Debian) and tests the package for the following base images: debian:buster ubuntu:focal
The PR is designed to work both directly in the local repo and Azure Dev Ops.
This PR is part of a series of 5 initial PRs that will provide packages for all the common managers on the common OSes (Linux, Windows and Mac). Follow up PRs will provide packages for less common configs.
Execute the following command from the root directory of this repository:
./release/linux/deb/pipeline.sh
Output will be sent to ./output/deb
To test the packages:
./release/linux/deb/pipeline-test.sh
A follow up PR will publish the .debs to packages.microsoft.com for public download

Debian(Buster/Stretch/Jessie)/Ubuntu(Focal/Bionic/Xenial)/Apt packages

---

pkg/sqlcmd/batch.go
pkg/sqlcmd/batch_test.go

I don't know why I put this code in batch.go in the first place.
Fixes #95

do not treat \ as escape character in strings

---

cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
pkg/sqlcmd/sqlcmd.go

**Summary:**
This PR addresses the issue #101.
An appropriate exit code has been set and error is printed if the input file specified for '-i' is missing.
**Validation**
```
go-sqlcmd>sqlcmd.exe -i missing.sql >stdout.txt 2>stderr.txt
go-sqlcmd>type stderr.txt
Sqlcmd: Error:  Error occurred while opening or operating on file missing.sql (Reason: open missing.sql: The system cannot find the file specified.).
go-sqlcmd>echo %ERRORLEVEL%
1
```

Raise error for missing input file

---

cmd/sqlcmd/main.go

This commit addresses issue #102.
stderr messages when redirected to stdout would not contain the EOL, causing the prompt to appear on the line as the stderr message.
With existing go-sqlcmd
```
$ sqlcmd -r0
1> select @@version1
2> go
Must declare the scalar variable "@@version1".1>
```
After the changes in PR
```
git\go-sqlcmd>sqlcmd -r0
1> select @@version1
2> go
Must declare the scalar variable "@@version1".
1>
```

Add newline for stderr messages

---

cmd/sqlcmd/main.go
cmd/sqlcmd/main_test.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/connect.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

In absence of console or when console reference line is set
to nil, noPwd is set to true which disables password prompt
and when console is not initialized, password cannot be read
from user. This is why when -i is specified, console is not
initialized and we do not see password prompt.
This commit initializes console even if -U is specified so
that password can be read interactively from user.
Resolves #115 
Validation:
```
go-sqlcmd>.\sqlcmd.exe -i test.sql -U sa
Password:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL …
```

Initialize console if -U is specified

---

build/azure-pipelines/build-product.yml

Fixes #129 
I don't have an IBM Z to test with so I hope the fact that it compiles for s390x means it works :-)

Add s390x build

---

build/azure-pipelines/build-product.yml

We don't want to trigger a product build for every merge to main. I misunderstood how the trigger works; the tag filter is 'or' not 'and'.

remove branch filter for build

---

cmd/sqlcmd/main.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/sqlcmd.go

I can't quite figure out how to make `-X [1]` work with Kong, so for now I'm staying with `-X`  and warning when a sys command used.

block sys commands on -X

---

pkg/sqlcmd/batch.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/exec_darwin.go
pkg/sqlcmd/exec_linux.go
pkg/sqlcmd/exec_windows.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/variables.go

`:ed` is a system command
```
e:\git\go-sqlcmd\cmd\sqlcmd>sqlcmd -S davidshi-2019 -X
1> ed
Sqlcmd: Error: ED and !!<command> commands, startup script, and environment variables are disabled.
```
Also, preserve blank lines from input.
Pre-fix:
```
e:\git\go-sqlcmd\cmd\sqlcmd>.\sqlcmd
1> select 100
2>
2>
2>
2>
2> select 200
3> :list
select 100
select 200
3>
```
ODBC:
```
e:\git\go-sqlcmd\cmd\sqlcmd>"C:\Program Files\Microsoft SQL Server\110\Tools\Binn\SQLCMD.EXE"
1> select 100
2>
3>
4>
5>
6> select 200
7> :list
select 100
select 200
7>
```
With Fix:
```
e:\git\go-sqlcmd\cmd\sqlcmd>.\sqlcmd
1> select 100
2>
3>
4>
5>
6> select 200
7> :list
select 100
select 200
7>
```

Implement `:ED`

---

cmd/sqlcmd/main.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

Customer feedback from a financial services company - 
`!!` shouldn't require a space after it, and `-M` should just be ignored.

Stub -M and fix !!

---

pkg/sqlcmd/batch_test.go
pkg/sqlcmd/errors.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

This commit addresses #144 
A dummy function IsSqlcmdErr() has been added in SqlcmdErr interface 
to distinguish Sqlcmd errors from server errors. 
The only purpose of it is to distinguish SqlcmdErr interface from the 
generic Error interface. From now on all sqlcmd errors should implement
SqlcmdErr interface to distinguish itself from other errors.

Refactor and separate sqlcmd errors from server erros

---

README.md

In this context, 'Go' is the name of a programming language.  Thus, it is a proper noun, and such are typically capitalized in English.  Further, [the language's maintainers](https://go.dev/) capitalize it.

Capitalize proper noun in README

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

https://github.com/microsoft/go-sqlcmd/issues/179
When a user specifies following command :
"sqlcmd on-error.sql -b"
In on-error.sql :
:ONERROR ignore
select @@versionn
GO
select @@version
GO
Actual Output : It is exiting with error code.
Expected Output : It should run with only printing error message

on error ignore precedence over -b

---

cmd/modern/main.go

This commit addresses #183.
```
git\go-sqlcmd\cmd\modern>.\sqlcmd.exe
1> select @@version
2> go
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)
Apr 29 2022 18:00:13
Copyright (C) 2019 Microsoft Corporation
Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22621: ) (Hypervisor)
(1 row affected)
```

Check sub-command for modernCLI only if specified

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

ONERROR -> replaced with on error for naming connvention matching with ODBC

on error name back-compat with odbc

---

pkg/sqlcmd/variables.go
pkg/sqlcmd/variables_test.go

allow var names to start with _

---

cmd/modern/options.go

Remove unused var, which is being picked up by the GitHub action (but not being picked up by the PR pipelines).  (longer term we need to work out why this happend, why is something getting flaged post merge)

Remove unused globaloptions var

---

.gitignore
build/arch.txt
build/azure-pipelines/build-product.yml
build/build.cmd
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_windows_amd64.go

Fixes #224 
Fixes #223 
Updates `build\build.cmd` to run all the crossplatform builds to test locally before pushing a PR.

Fix ARM64 builds

---

cmd/modern/main.go
internal/config/context.go
internal/config/user.go

sqlcmd when invoked with no arguments, executes in backward compat mode and ignore current-context info for establishing connection. This commit changes the default behavior to establish connection to the endpoint associated with current-context if valid user details exits in sqlcmd config file.
This ensures that users can connect to sql server instance created by sqlcmd if no arguments are specified while invoking sqlcmd.
```
\git\go-sqlcmd>.\sqlcmd.exe
1> select @@servername
2> go
--------------------------------------------------------------------------------------------------------------------------------
LAPTOP-VPBI3ASB
(1 row affected)
1> exit
git\go-sqlcmd>.\sqlcmd.exe create mssql --accept-eula
Downloading mcr.microsoft.com/mssql/server:latest
Starting …
```

Establish conn to curret-context if no args given

---

cmd/modern/main.go

If users have set SQLCMDPASSWORD as part of normal sqlcmd usage, we were using that, when SQLCMDUSER was not set (and setting SQLCMDUSER from sqlconfig file), this was causing login failures.

Don't use SQLCMDPASSWORD env var if SQLCMDUSER env var not set

---

cmd/modern/main.go
internal/config/config.go

It's possible for the user shell to have no $HOME/%USERPROFILE% env var. This closes #279.  We need to cope with this:
1. We will use "." (current working directory), as the default dir to place the .sqlcmd/sqlconfig file in, can be overriden using --sqlconfig (when in the modern CLI)
2. When running in legacy mode, we won't try to read the sqlconfig file if it doesn't exist in the default location (which requires the %HOME/%USERPROFILE% envvar), we also won't create an empty sqlconfig file in this case.

Cope with no HOME env var in user shell

---

NOTICE.md
README.md
go.mod
go.sum
internal/color/color.go
internal/color/color_test.go
pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go
pkg/sqlcmd/format.go
pkg/sqlcmd/format_test.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/variables.go

- use `SQLCMDCOLORSCHEME` variable to identify the style/scheme name that matches one defined by the [chroma styles]<https://github.com/alecthomas/chroma/styles> package
- Add a `:list color` command to print samples of TSQL syntax in each scheme
- Colorizes query results and errors as well

Add console syntax coloring

---

cmd/modern/root/uninstall.go

This PR allows the `sqlcmd delete` to succeed even if the user has manually deleted the container using something like `docker rm`.  sqlcmd will log a warning if it finds the container has already been removed, and will continue to delete the context (and endpoint/user) and will complete successfullly
Closes #282

Allow sqlcmd delete to succeed if container has already been deleted

---

.pipelines/include-install-go-tools.yml
build/azure-pipelines/build-common.yml
build/azure-pipelines/build-product.yml
build/azure-pipelines/package-common-create.yml
build/azure-pipelines/package-common-test.yml
build/azure-pipelines/package-product.yml
release/linux/deb/pipeline.sh
release/linux/docker/pipeline.sh
release/linux/rpm/pipeline.sh
release/windows/msi/product.wxs
release/windows/msi/scripts/pipeline-test.ps1
release/windows/msi/scripts/pipeline.cmd

1. Add LICENSE/NOTICE.md to the install directory on Windows .msi installs (winget/choco)
2. Add arm/arm64 .msi builds (a separate winget repo PR adds these to the winget installer)
3. Also, align Architecture naming to winget/brew/debian:
So we will have:
x64 (for Windows/Mac)
amd64 (for Linux)
x86 (for Windows/Mac)
arm (for all Platforms)
arm64 (for all Platforms)
Sources:
https://github.com/jedieaston/winget-cli/blob/0384fcd3657942f59bc94aae3dd888742f9ef632/schemas/JSON/settings/settings.schema.0.2.json#L58
"enum": [
"neutral",
"x64",
"x86",
"arm64",
"arm"
],
This also seems to be align with brew:
https://github.com/Homebrew/homebrew-core/blob/361429d75bf64c698c3d971f7aeebe01cedb87c2/Formula/sqlcmd.rb
sha256 cellar: :any_skip_relocation, arm64_ventura:  
sha256 cellar: …

Add LICENSE/NOTICE.md to sqlcmd install folder

---

cmd/modern/root/install/mssql-base.go
internal/container/controller.go
internal/container/controller_test.go

Adds
--architecture string             Specifies the image CPU architecture (default "amd64")
--os string                       Specifies the image operating system (default "linux")
This should fix an issue on some Apple silicon machine (M1/M2) that seems to require these settings to be passed into the container create command
Closes #283

Pass --platform information into Container Create

---

NOTICE.md
pkg/sqlcmd/sqlcmd_test.go

Error `15001` was a bad choice because until recently it had an incorrect format specifier for its parameter. That specifier has been fixed in Azure SQL Database so it can only be raised with a proper parameter. Switching to `15002` with a valid parameter to pass on all editions.

Update NOTICE and a test

---

README.md

- Removed "Preview" from the heading
- Added `choco` package manager instructions
- Add temporary instructions to workaround `winget upgrade` not working
- Added info on switches/command not implemented yet

README updates for v1

---

internal/config/context.go

This commit fixes #339 
`sqlcmd config add-user` command by default assumes basic authentication type but in case a user is created with auth type other than "basic" then connection will be established to endpoint mentioned by current-context (which is existing behavior) and further auth info won't be read as auth type "other" is not supported yet.

Do not read basic auth info if auth type is other

---

cmd/sqlcmd/sqlcmd.go

Linked Issue : https://github.com/microsoft/go-sqlcmd/issues/344
Resumed Help description as :
-? shows this syntax summary, --help shows modern sqlcmd sub-command help

help text message resumed

---

cmd/sqlcmd/sqlcmd.go

Related to issue : https://github.com/microsoft/go-sqlcmd/issues/343
Removed Extra error commands and usage print.
Before PR changes :
C:\src\go-sqlcmd\cmd\modern>sqlcmd --encrypt-connection yes
--encrypt-connection must be one of "default","false","true","disable" but got "yes"
Error: --encrypt-connection must be one of "default","false","true","disable" but got "yes"
Usage:
[flags]
Flags:
-N, -- string                         This switch is used by the client to request an encrypted connection. (default "default")
-K, --application-intent string       Declares the application workload type when connecting to a server. The only currently supported value is ReadOnly. If -K is not specified, the sqlcmd utility will not support connectivity to a secondary replica in an Always On …

removing extra error and usage print

---

cmd/sqlcmd/sqlcmd.go

Related issue : 
https://github.com/microsoft/go-sqlcmd/issues/342

removing extra screenwidth entry

---

pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go
pkg/sqlcmd/sqlcmd_windows_amd64.go

Fixes #373 
I don't know how I missed this behaviour when I added npipe to go-mssqldb.

fix: use TCP as default protocol

---

.vscode/launch.json
README.md
build/build.cmd
cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go
internal/localizer/constants.go
internal/translations/catalog.go
internal/translations/catalog_test.go
internal/translations/locales/de-DE/messages.gotext.json
internal/translations/locales/de-DE/out.gotext.json
internal/translations/locales/en-US/out.gotext.json
internal/translations/locales/es-ES/messages.gotext.json
internal/translations/locales/es-ES/out.gotext.json
internal/translations/locales/fr-FR/messages.gotext.json
internal/translations/locales/fr-FR/out.gotext.json
internal/translations/locales/it-IT/messages.gotext.json
internal/translations/locales/it-IT/out.gotext.json
internal/translations/locales/ja-JP/messages.gotext.json
internal/translations/locales/ja-JP/out.gotext.json
internal/translations/locales/ko-KR/messages.gotext.json
internal/translations/locales/ko-KR/out.gotext.json
internal/translations/locales/pt-BR/messages.gotext.json
internal/translations/locales/pt-BR/out.gotext.json
internal/translations/locales/ru-RU/messages.gotext.json
internal/translations/locales/ru-RU/out.gotext.json
internal/translations/locales/zh-CN/messages.gotext.json
internal/translations/locales/zh-CN/out.gotext.json
internal/translations/locales/zh-TW/messages.gotext.json
internal/translations/locales/zh-TW/out.gotext.json

Fixes #365 
Fixes #196 
Fixes #362 
I've also standardized more of the invalid flag error messages and replaced the default Cobra errors with localizable errors prefixed with `Sqlcmd: `

feat:Add -P -y -Y flags

---

internal/translations/LocProject.json

This commit update the language IDs so that the localization artifacts are generated 
in same directories as the ones generated by Golang localization framework.
The output path is intentionally kept different to make sure that the initial pipeline
run does not affect the existing builds which contains partial localized data.
The localization team will checkin the localized artifacts in the output path.
We will keep the content received from localization team and the one used by our builds 
in sync via script.

Update localization settings

---

cmd/modern/root/open/ads_darwin.go

Mac builds failed with following error
```
root/open/ads_darwin.go:31:14: undefined: localizer
##[error]The Go task failed with an error: Error: The process '/Users/runner/hostedtoolcache/go/1.18.0/x64/bin/go' failed with exit code 2
```
VS Code did not throw errors/warning as it warned that this file is within mdule "." which is not included in workspace.

Fix mac builds

---

README.md
cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go

Fixes #348 
Short of completely rewriting the command line parser and ignoring Cobra, we are subject to a fair number of limitations for backward compatibility.
Of note:
- The `os.Args` array doesn't give any clue whether the argument was passed in quotes.
- Cobra doesn't parse the raw command line, it relies on the args array and its limitations.
This fix increases the number of command line variants that will be ODBC compatible but is far from exhaustive.
Users who don't use commas and dashes in their file names will be fine using space-delimited arguments for `-i`.

Fix: space delimited args for -i and -v

---

go.mod
go.sum

Pick up go-mssqldb v1.5.0 to get the fix

fix: Support extended chars in instance names

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

Fixes #454 
Simply appends the query parameter to the current batch before running the query and exiting.

fix: EXIT parameter merge with current batch

---

cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go
internal/translations/catalog.go
internal/translations/locales/de-DE/out.gotext.json
internal/translations/locales/en-US/out.gotext.json
internal/translations/locales/es-ES/out.gotext.json
internal/translations/locales/fr-FR/out.gotext.json
internal/translations/locales/it-IT/out.gotext.json
internal/translations/locales/ja-JP/out.gotext.json
internal/translations/locales/ko-KR/out.gotext.json
internal/translations/locales/pt-BR/out.gotext.json
internal/translations/locales/ru-RU/out.gotext.json
internal/translations/locales/zh-CN/out.gotext.json
internal/translations/locales/zh-TW/out.gotext.json
pkg/sqlcmd/connect.go
pkg/sqlcmd/sqlcmd.go

Fixes #458 
Like the old sqlcmd, `-Z` and `-z` are not mutually exclusive, but `-Z` trumps `-z`
If the user doesn't provide `-P`, `-z`, or '-Z' and the interactive connection fails with error 18488 we prompt the user for a new password.

feat: Change Password

---

README.md
cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go

Fixes #430 
Validation:
With unknown CA
```
git\go-sqlcmd>.\sqlcmd.exe -Slocalhost:1434 -Usa -P<masked> -N "strict"
TLS Handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority
TLS Handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority
git\go-sqlcmd>.\sqlcmd.exe -Slocalhost:1434 -Usa -P<masked> -N "strict" -C
TLS Handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority
TLS Handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority
```
With known CA
```
git\go-sqlcmd>.\sqlcmd.exe -S<redacted>.database.windows.net:1433 -U<masked> -P<masked> -N "strict"
1> select @@version
2> go …
```

Add -N strict option

---

internal/translations/catalog.go
internal/translations/locales/de-DE/messages.gotext.json
internal/translations/locales/de-DE/out.gotext.json
internal/translations/locales/es-ES/messages.gotext.json
internal/translations/locales/es-ES/out.gotext.json
internal/translations/locales/fr-FR/messages.gotext.json
internal/translations/locales/fr-FR/out.gotext.json
internal/translations/locales/it-IT/messages.gotext.json
internal/translations/locales/it-IT/out.gotext.json
internal/translations/locales/ja-JP/messages.gotext.json
internal/translations/locales/ja-JP/out.gotext.json
internal/translations/locales/ko-KR/messages.gotext.json
internal/translations/locales/ko-KR/out.gotext.json
internal/translations/locales/pt-BR/messages.gotext.json
internal/translations/locales/pt-BR/out.gotext.json
internal/translations/locales/ru-RU/messages.gotext.json
internal/translations/locales/ru-RU/out.gotext.json
internal/translations/locales/zh-CN/messages.gotext.json
internal/translations/locales/zh-CN/out.gotext.json
internal/translations/locales/zh-TW/messages.gotext.json
internal/translations/locales/zh-TW/out.gotext.json

Adding newly localized messages

Consume new localized messages

---

cmd/modern/root/config/connection-strings.go
cmd/modern/root/install/mssql-base.go
cmd/modern/root/open/ads.go
cmd/modern/root/open/ads_windows.go
internal/net/net.go
internal/net/net_test.go
internal/sql/mssql.go
internal/translations/catalog.go
internal/translations/locales/de-DE/out.gotext.json
internal/translations/locales/en-US/out.gotext.json
internal/translations/locales/es-ES/out.gotext.json
internal/translations/locales/fr-FR/out.gotext.json
internal/translations/locales/it-IT/out.gotext.json
internal/translations/locales/ja-JP/out.gotext.json
internal/translations/locales/ko-KR/out.gotext.json
internal/translations/locales/pt-BR/out.gotext.json
internal/translations/locales/ru-RU/out.gotext.json
internal/translations/locales/zh-CN/out.gotext.json
internal/translations/locales/zh-TW/out.gotext.json

Closes #485 
```
\git\go-sqlcmd>.\sqlcmd.exe create mssql --accept-eula
Downloading mcr.microsoft.com/mssql/server:latest
Starting mcr.microsoft.com/mssql/server:latest
Created context "mssql" in "C:\Users\apdeshmukh\.sqlcmd\sqlconfig", configuring user account...
Disabled "sa" account (and rotated "sa" password). Creating user "apoorvdeshmukh"
Now ready for client connections on port 1435
HINT:
1. Open in Azure Data Studio: sqlcmd open ads
2. Run a query:               sqlcmd query "SELECT @@version"
3. Start interactive session: sqlcmd query
4. View sqlcmd configuration: sqlcmd config view
5. See connection strings:    sqlcmd config connection-strings
6. Remove:                    sqlcmd delete
```

Correct format specifier for port

---

NOTICE.md
README.md
cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go

treat `-N` by itself as `-N true`
Fixes #497

Backward compat support for -N

---

.github/workflows/pr-validation.yml
NOTICE.md
build/azure-pipelines/build-common.yml
go.mod

Fixes #499 (though I don't think that CVE is relevant since we don't use `cgo`)
We should use a new toolset anyway.

update Go  tools to 1.21

---

pkg/sqlcmd/batch.go
pkg/sqlcmd/batch_test.go

fix parsing of multiline strings

---

.github/workflows/golangci-lint.yml
pkg/sqlcmd/batch.go
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

Fix: Apply x flag during batch parsing

---

cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go

Handle multiple `-i` and `-v` entries correctly when they are followed by a flag-without-space like `-isomefile1 somefile2 -V10`

fix: Parse list flags correctly

---

cmd/sqlcmd/sqlcmd.go
cmd/sqlcmd/sqlcmd_test.go

Would this be a good fix for the issue #525 when both -Q and -q are specified.
By switching priority, when both are specified, it takes -Q first, and finishes. The app no more crashes.
If we would like to report error instead, maybe I could do it in another PR.
Example output
```
> ./sqlcmd -S "tcp:127.0.0.1,1433" -E -d master -q "SELECT 1" -Q "SELECT 2"
-----------
2
(1 row affected)
```

fix: When both -Q and -q are specified, take -Q input and finish

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

Fixes #546 
Since our sqlcmd doesn't have a real grammar like the ODBC sqlparser we have to special case some aspects of the syntax. 
The sqlcmd syntax isn't clearly documented either.

omit comments from commands

---

.github/workflows/pr-validation.yml
.pipelines/include-install-go-tools.yml
go.mod
go.sum
pkg/sqlcmd/sqlcmd.go
pkg/sqlcmd/sqlcmd_test.go

- Fixes #556 
- Updates go-mssqldb to 1.8

Print headers when zero rows are returned

---

go.mod
go.sum
internal/container/controller.go

This is to update version of docker/docker to address [CVE-2024-36623](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2024-36623), docker/docker version 25.0.6 is vulnerable to Race Condition vulnerability.

bump to docker v27.3.1+incompatible

---

pkg/sqlcmd/commands.go
pkg/sqlcmd/commands_test.go

Fix: Make colon optional for reset
